### ISSUE TITLE
THULAC的Java 8实现thulac4j

### ISSUE THREAD

**Issue by yizhiru** [thunlp/THULAC-Java#11]
[thulac4j](https://github.com/yizhiru/thulac4j)是THULAC的Java 8实现，做了如下的优化：

1. 规范化分词词典，并去掉一些无用词；
2. 重写DAT（双数组Trie树）的构造算法，生成的DAT size减少了8%左右，从而节省了内存；
3. 简明化分词流程，便于功能扩展。

欢迎大家对比使用。

**Comment by std4453** [comment]
您好，感谢您对本库的支持，对于您的提议，有几点问题有待解决，谢谢配合：
1. 本库在上次的重构中修改颇多，而据观察您的代码与本库的代码差异较大，直接merge容易导致兼容性问题。请修改您的代码以适应本库的项目结构与API，以便相关人员能够更好的理解。
2. java8主要是在代码的功能性API上有所更新，在大范围内的支持仍不广泛。目前只在测试类中使用了java8功能，其余部分任然以兼容java7甚至java6为目标。
3. 由于本库的model v3中提供了训练代码，因此请问能否提供任意原版DAT文件到新版DAT文件的转换的代码，以便其他用户使用。此外能提供相应的profiler代码证明新版DAT的性能优势吗？谢谢！
4. 有可能的话，请尽量以pull request的方法提供您的修改，一方面方便我们的人员对比修改前后的差距，另一方面也可以充分利用github的功能提高效率，两全其美。

**Comment by zibuyu** [comment]
我看这些feature与现在主项目并不冲突。欢迎将相关feature merge到该主项目下，大家集中力量一起把工具做得更好。如果 @yizhiru 没有精力，可以请 @gzp9595 @std4453 @MaJunhua 来帮忙。:)

**Comment by yizhiru** [comment]
@std4453 
1. thulac4j是从头开始写的，与THULAC-Java的风格差异存在着较大出入，若merge到一起，的确不太合适。

2. 对于22万多词，THULAC-Java构造的DAT size为103万，而thulac4j构造的只有93万左右，在构造时间上二者没有显著差异。当时测试的具体数字没有保存，可以跑两者的DatMaker类以验证。（等有时间了，我更新一下）

3. 原版DAT（包括训练模型）到新版的转换，我会在下一个版本放出来。（这个建议挺不错的）

**Comment by hfzyethan** [comment]
冒昧问下，训练代码在哪呢？没找到 @std4453
