### ISSUE TITLE
各种问题不忍吐槽

### ISSUE THREAD

**Issue by std4453** [thunlp/THULAC-Java#5]
这些都是曾经的THULAC-Java的问题，现在已经解决掉绝大部分了。

一个库应该有一个作为根的包就够了，为什么现在有四个。。
> 以下是针对thulac.java的吐槽

`thulac.java`为什么是小写的，里面既有profiler还有实际逻辑，然后根本没有一个可以直接调用的API，我想直接提取分词的结果还得用文件系统中转一下。
变量命名完全不符合规范，虽然是直接从c++翻译过来的库，但也不应该这样啊。。
为什么输入文件的字符集是硬编码的，而且还不是最常用于中文的GB2312而是UTF-8，这是在逼我先把文件读进来一遍再用UTF8输出一遍吗。。
命令行容错也很捉急，比如输入的是`-input -seg_only ...`的话，input_file就是`-seg_only`，后面用InputStreamReader的时候就会FileNotFound，然而这个时候程序并没有终止，接下来在getRaw里面就会报NullPointerException。反正各种地方出了错就直接printStackTrace然后无视掉了，既没有finally块也不终止程序，这样问题很大的知道吗。
FileOutputStream out开了不关也是厉害，虽然Closable在finalize的时候会被关闭掉，但是如果程序本身崩溃（比如上面说的NullPointerException的情况）的话就会直接退出而导致系统资源泄露。
getRaw里面Pattern每次执行到就要重新compile一遍也是真的嫌cpu太快，好歹做个静态的字段缓存一下啊。
代码风格也是。。大括号换不换行，运算符前后加不加空格这种，都是IDE里面一步Format Code就能搞定的事情，难道vim用得太爽不惜发动圣战也要乱写？
各种常量就当做magic number摆在那里真的好吗。。真的不考虑弄个properties文件不用重编译就能调参数吗。。
其他各种小毛病也是一大堆，反正怎么跟best practice不对付就怎么来。。
比如遍历Vector完全可以用自动代码糖的Iterator，非要用for循环，还不把size先提取出来。
比如区别控制台和输出到文件也是直接硬编码，完全可以用PrintWriter把out包一层然后就和System.out是同一个类型了，非要加一个判断然后把同样的代码逻辑写两遍，敢问有人听说过DRY原则吗？
对了明明在main的方法签名里面声明了throws IOException又把所有可能出IOException的地方都直接catch掉是几个意思。。

总之，我现在非常好奇的是，清华的实力到底是怎么样的。。

**Comment by fanzhuyifan** [comment]
**1. 建议添加注释，要不然像现在通篇没有注释既不便于使用，又不便于维护。**

2. github文档中中的词性解释是这样的：

n/名词 np/人名 ns/地名 ni/机构名 nz/其它专名
m/数词 q/量词 mq/数量词 t/时间词 f/方位词 s/处所词
v/动词 vm/能愿动词 vd/趋向动词 a/形容词 d/副词
h/前接成分 k/后接成分 i/习语 j/简称
r/代词 c/连词 p/介词 u/助词 y/语气助词
e/叹词 o/拟声词 g/语素 w/标点 x/其它

而实际测试：
我觉得吧，如果非要我说一句话试试看的话，我一定会这么说：苟利国家生死以，岂因祸福避趋之。
输出结果为：
我_r 觉得_v 吧_u ，_w 如果_c 非_d 要_v 我_r 说_v 一_m 句_q 话_n 试试_v 看_v 的_u 话_n ，_w 我_r 一定_d 会_v 这么_r 说_v ：_w 苟利国家生死以_id ，_w 岂因祸福避趋之_id 。_w 
可见习语代码为"id"，而非"i",与文档中不符。
**建议核查词性解释。**

**Comment by gzp9595** [comment]
非常感谢您对THULAC的支持~
针对您提出的问题和建议，我们会尽快改正并完善。我们也会多了解各种语言的编写规则，尽可能的将THULAC完善，方便大家使用。
同时，也非常欢迎您加入我们维护的队伍中，改进THULAC工具~

**Comment by ice1000** [comment]
遍历Vector还可以forEach啊。。。
之前还准备看这个学习来着，结果看了issue主的吐槽，实在是太有画面感了。。。。

（路过一波）

**Comment by zibuyu** [comment]
感谢对该工具包的批评，我们会尽快改进。希望以后能继续得到来自各位的指正。:)

**Comment by std4453** [comment]
PR今天merge掉了，也算做出了一个交代吧。相信修改过一番之后已经解决了这里面说的绝大部分的问题了，希望能够帮助到各位。总而言之，talk is cheap, show me the code.
