### ISSUE TITLE
添加注释&核查词性解释

### ISSUE THREAD

**Issue by fanzhuyifan** [thunlp/THULAC-Java#6]
1.**建议添加注释，要不然像现在通篇没有注释既不便于使用，又不便于维护。**

2.
github文档中中的词性解释是这样的：

> n/名词 np/人名 ns/地名 ni/机构名 nz/其它专名
> m/数词 q/量词 mq/数量词 t/时间词 f/方位词 s/处所词
> v/动词 vm/能愿动词 vd/趋向动词 a/形容词 d/副词
> h/前接成分 k/后接成分 **i/习语** j/简称
> r/代词 c/连词 p/介词 u/助词 y/语气助词
> e/叹词 o/拟声词 g/语素 w/标点 x/其它

而实际测试：

> 我觉得吧，如果非要我说一句话试试看的话，我一定会这么说：苟利国家生死以，岂因祸福避趋之。

 输出结果为：

> 我_r 觉得_v 吧_u ，_w 如果_c 非_d 要_v 我_r 说_v 一_m 句_q 话_n 试试_v 看_v 的_u 话_n ，_w 我_r 一定_d 会_v 这么_r 说_v ：_w 苟利国家生死以_id ，_w 岂因祸福避趋之_id 。_w

**可见习语代码为"id"，而非"i",与文档中不符。**
可能还有其他不一致之处，我未全部核查。
**建议核查并且修改词性解释。**

**Comment by gzp9595** [comment]
非常感谢您对THULAC工具的支持~
我们会尽快整理THULAC工具代码，并重新附上相应的注释，方便用户理解和使用。
