### ISSUE TITLE
thulac.java中一些问题： maxLength过大导致长段文字未分词. seg_only时无法自定义分隔符.建议增加正则表达式Pattern p匹配的标点符号

### ISSUE THREAD

**Issue by fanzhuyifan** [thunlp/THULAC-Java#7]
现在程序中maxLength=50000，测试分词:

```
String[] args = {"-t2s","-seg_only","-deli","_","-input",“input.txt”,"-output","output.txt",
				"-model_dir","/Users/XXXX/models"};
thulac.main(args);
```

其中input.txt为：

> 一位真正的作家永远只为内心写作，只有内心才会真实地告诉他，他的自私、他的高尚是多么突出。内心让他真实地了解自己，一旦了解了自己也就了解了世界。很多年前我就明白了这个原则，可是要捍卫这个原则必须付出艰辛的劳动和长时期的痛苦

输出分词结果为：

> 一位真正的作家永远只为内心写作，只有内心才会真实地告诉他，他的自私、他的高尚是多么突出。内心让他真实地了解自己，一旦了解了自己也就了解了世界。很多年 前 我 就 明白 了 这个 原则 ， 可是 要 捍卫 这个 原则 必须 付出 艰辛 的 劳动 和 长 时期 的 痛苦 ， 因为 内心 并非 时时刻刻 都 是 敞开 的 ， 它 更 多 的 时候 倒是 封闭 起来 ， 于是 只有 写作 ， 不 停 地 写作 才 能 使 内心 敞开 ， 才 能 使 自己 置身 于 发现 之中 ， 就 像 日出 的 光芒 照亮 了 黑暗 ， 灵感 这时候 才 会 突然 来到 。

**问题：**

1. 分割词为“ ”，而非自定义的“_”
2. 长段文字未分词

**对于解决问题2的建议**

1. 如果maxLength没有什么存在必要的话，建议去除，因为它明显降低长句时分词正确性。建议在public static Vector<String> getRaw中，永远对标点符合进行识别，而不进行if(ans.length() < maxLength)的比较
2. 建议将public static Vector<String> getRaw中正则表达式识别如下修改：

`Pattern p = Pattern.compile(".*?[：\\.．。？！；;!?，,、 \"\'“”‘’\n\r【】《》");`

以识别更全的标点符号(可考虑在此基础上增添其他符号，但是中文常用的、“”‘’""不能少！)
原文件为：

`Pattern p = Pattern.compile(".*?[。？！；;!?]");`

修改后运行结果：(同时将maxLength值设为1)

> 一 位 真正 的 作家 永远 只 为 内心 写作 ， 只有 内心 才 会 真实 地 告诉 他 ， 他 的 自私 、 他 的 高尚 是 多么 突出 。 内心 让 他 真实 地 了解 自己 ， 一旦 了解 了 自己 也 就 了解 了 世界 。 很多年 前 我 就 明白 了 这个 原则 ， 可是 要 捍卫 这个 原则 必须 付出 艰辛 的 劳动 和 长 时期 的 痛苦 ， 因为 内心 并非 时时刻刻 都 是 敞开 的 ， 它 更 多 的 时候 倒是 封闭 起来 ， 于是 只有 写作 ， 不 停 地 写作 才 能 使 内心 敞开 ， 才 能 使 自己 置身 于 发现 之中 ， 就 像 日出 的 光芒 照亮 了 黑暗 ， 灵感 这时候 才 会 突然 来到 
>。

**Comment by fanzhuyifan** [comment]
用lite版本的model竟然会把整句“仿佛是道听途说般地只记得零星几点”判断成一个词性为t的东西？！！而输入“仿佛是道听途说般地只记得”，分词结果为“仿佛_d 是_v 道听途说_id 般_u 地_u 只_d 记得_v ”，非常正确。但加了“零星几点“后就分不出来了。不知道这是不是只是lite版的model的问题，还是完整版的model也有这个问题。

**Comment by gzp9595** [comment]
非常感谢您对THULAC的支持~
关于问题1，"-deli"是分词的结果和分词的词性之间的区分符，在分词模式是不使用的~
对于问题2，我们也在考虑将maxLenght去掉，会在近期测试后给出好的解决方案~

对于问题3（最后的分词bug）已经修复，非常感谢您的问题
